### ISSUE TITLE
Nonlinear inverse

### ISSUE THREAD

**Issue by jackt3** [tomfrankkirk/regtricks#2]
When inverting a nonlinear warp, the NotImplementedError here is raised: https://github.com/tomfrankkirk/regtricks/blob/ce1db6998a5c1bdc0f414af7c17aa3d50fa0e718/regtricks/transforms/nonlinear.py#L39-L40

Should this line specify "from_fnirt"?
https://github.com/tomfrankkirk/regtricks/blob/ce1db6998a5c1bdc0f414af7c17aa3d50fa0e718/regtricks/transforms/nonlinear.py#L123

**Comment by tomfrankkirk** [comment]
Good spot, and you were correct. Just pushed a fix on pypi, latest version is now regtricks-0.3.0.post20
