### ISSUE TITLE
rt.chain of linear motion correction and non-linear registration raises TypeError

### ISSUE THREAD

**Issue by jackt3** [tomfrankkirk/regtricks#3]
When using rt.chain() to chain together a linear motion correction and a nonlinear registration we get a TypeError.

The combined transformation is constructed on the line below. https://github.com/tomfrankkirk/regtricks/blob/df48d5319779386211fa6894360ad5accaa640eb/regtricks/multiplication.py#L124-L125

In the given case, `constructor` is set as `NonLinearMotionCorrection` a few lines above.
https://github.com/tomfrankkirk/regtricks/blob/df48d5319779386211fa6894360ad5accaa640eb/regtricks/multiplication.py#L121

`NonLinearMotionCorrection` inherits from `NonLinearRegistration` and when this parent-class is inherited below, a TypeError is raised because `warp`, `src` and `ref` haven't been provided.
https://github.com/tomfrankkirk/regtricks/blob/df48d5319779386211fa6894360ad5accaa640eb/regtricks/transforms/nonlinear.py#L243

**Comment by tomfrankkirk** [comment]
Good spot! turns out the super().init() isn't needed at all, because just taking the warp object from the non linear registration is enough (it carries its own reference to src and ref internally). New version is on pypi v0.3.3, works against the test cases I have set up.
